### ISSUE TITLE
Compile error in Unity 2019.4.40

### ISSUE THREAD

**Issue by RichardsATcn** [gilzoide/unity-sqlite-net#12]
string message = Marshal.PtrToStringUTF8(messagePtr);

Assets\unity-sqlite-net-1.0.0-preview10\Runtime\SQLiteConfig.Log.cs(19,38): error CS0117: 'Marshal' does not contain a definition for 'PtrToStringUTF8'
![image](https://github.com/gilzoide/unity-sqlite-net/assets/8119891/0f7dc994-5ec6-42e8-b419-abc42851a829)

**Comment by RichardsATcn** [comment]
i modify  code  ：
![image](https://github.com/gilzoide/unity-sqlite-net/assets/8119891/ecf31fa8-1135-4a60-9d0c-04e59374e1f7)

**Comment by gilzoide** [comment]
Hey @RichardsATcn, thanks for the report!
It seems `Marshal.PtrToStringUTF8` is only available in .NET Standard 2.1, so Unity 2021.2+.
I'm reopening this issue because you fixed in your project locally, but other people will have the same problem if they use this, so we need to fix in the package and submit a new version for everyone.
