### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by ProggersValentino** [gilzoide/unity-sqlite-net#21]
Hey hope your doing well! 

Stumbled across this cool as repo which will be very handy for my project. But I see that there is no license attached (maybe I’m blind) so I thought I might ask if this be used commercially or not? 

If so would you mind adding the license?

**Comment by gilzoide** [comment]
Hey @ProggersValentino, thanks for asking.
SQLite is in the public domain, while SQLite-net itself is MIT licensed. In the start of this project, this were all the code in here, so I didn't bother to add a license.
But now we have first-party code with some method extensions, and I totally forgot to license them. I'll add it soon, so that you will definitely be able to use this commercially. I'll keep you posted when this happens =]

**Comment by ProggersValentino** [comment]
Amazing thank you sm!

**Comment by gilzoide** [comment]
Ok, so I added a LICENSE.txt file along with copyright notice for all first-party code, as well as added a note in README about all licenses of first-party and third-party code used by this project in commit 1864194901959a7d277df0e3858a58b78917c1e8.
I added a tag for version 1.0.1 that contains solely these licensing related changes, should be available in OpenUPM shortly.

Thanks again for the shoutout about this!
Cheers \o/
