### ISSUE TITLE
Unable to load dynamic library 'gilzoide-sqlite-net'

### ISSUE THREAD

**Issue by Hoper-Q** [gilzoide/unity-sqlite-net#33]
# BUGLog
Exception opening database connection: Unable to load DLL 'gilzoide-sqlite-net'. Tried the load the following dynamic libraries: Unable to load dynamic library 'gilzoide-sqlite-net' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = gilzoide-sqlite-net

I packaged it on one Linux computer and ran it on another Linux computer, and as a result, this error occurred.
But I`m sure it exist.
![Plugin](https://github.com/user-attachments/assets/90abf592-b21c-46de-a315-a34ba3f44f81)

**Comment by gilzoide** [comment]
Hey @Hoper-Q , thanks for the report.
Can you run the build on the "one Linux computer" you packaged the project or does it result in an error as well?

**Comment by Hoper-Q** [comment]
> 嘿，感谢您的报告。您能否在打包项目的“一台 Linux 计算机”上运行构建，还是也会导致错误？

The error does not occur on one machine, but it does on others.

**Comment by gilzoide** [comment]
> The error does not occur on one machine, but it does on others.

Hmm, ok, that's interesting 🤔
I have a Linux machine and SQLite-net also works in a build here.

Try something for me: on the machine that gives you error, run the following command and tell me if any dependencies could not be found:
```
ldd libgilzoide-sqlite-net.so
```
`ldd` prints the shared libraries required by the file, its dependencies. Each dependency found should have its address printed, and dependencies that are not found prints something like `not found`.

On my machine right now it displays like the following:
```
linux-vdso.so.1 (0x00007ffcdd5d8000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f8a7df77000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f8a7dd86000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007f8a7e213000)
```

**Comment by Hoper-Q** [comment]
> > The error does not occur on one machine, but it does on others.
> 
> Hmm, ok, that's interesting 🤔 I have a Linux machine and SQLite-net also works in a build here.
> 
> Try something for me: on the machine that gives you error, run the following command and tell me if any dependencies could not be found:
> 
> ```
> ldd libgilzoide-sqlite-net.so
> ```
> 
> `ldd` prints the shared libraries required by the file, its dependencies. Each dependency found should have its address printed, and dependencies that are not found prints something like `not found`.
> 
> On my machine right now it displays like the following:
> 
> ```
> linux-vdso.so.1 (0x00007ffcdd5d8000)
> libm.so.6 => /usr/lib/libm.so.6 (0x00007f8a7df77000)
> libc.so.6 => /usr/lib/libc.so.6 (0x00007f8a7dd86000)
> /usr/lib64/ld-linux-x86-64.so.2 (0x00007f8a7e213000)
> ```
![lddPlugins](https://github.com/user-attachments/assets/6fd839b9-54af-45de-9cf6-898825558b70)
Here.

**Comment by gilzoide** [comment]
@Hoper-Q thanks for the info. The problem really seems to be that the library was compiled against a newer version of glibc than your machine has available. This is not a thing that happens when building the Unity project, but rather when compiling the native plugin.

I see three options here:
1. You install a newer version of glibc in the machine and life goes on. At some point someone else will have the same problem and we'll go over this again and again...
2. We lower the version of glibc linked. I'm using a Docker container running Debian 12 and the latest version of the libc-dev package installed, it's possible to choose a previous version of it to lower the constraints and make it runnable on more devices.
3. Maybe instead of using glibc we can statically link musl. This would result in a bigger file, but remove the dependency on the libc dynamic library.

I'm quite busy for the next couple of weeks, but will try solutions 2 and 3 at some point. Feel free to also try it out and open a PR fixing loading on machines with lesser versions of glibc.

**Comment by Hoper-Q** [comment]
> @Hoper-Q thanks for the info. The problem really seems to be that the library was compiled against a newer version of glibc than your machine has available. This is not a thing that happens when building the Unity project, but rather when compiling the native plugin.
> 
> I see three options here:
> 
> 1. You install a newer version of glibc in the machine and life goes on. At some point someone else will have the same problem and we'll go over this again and again...
> 2. We lower the version of glibc linked. I'm using a Docker container running Debian 12 and the latest version of the libc-dev package installed, it's possible to choose a previous version of it to lower the constraints and make it runnable on more devices.
> 3. Maybe instead of using glibc we can statically link musl. This would result in a bigger file, but remove the dependency on the libc dynamic library.
> 
> I'm quite busy for the next couple of weeks, but will try solutions 2 and 3 at some point. Feel free to also try it out and open a PR fixing loading on machines with lesser versions of glibc.

Ok,Thanks.
